### ISSUE TITLE
Question about GPU requirement for training and code release

### ISSUE THREAD

**Issue by kunc01** [graphic-design-ai/graphist#1]
Congratulations to your solid work! I'm curious about GPU requirement for training Graphist-base, and is there any timeline for code&checkpoint release?

**Comment by zzhanghub** [comment]
Thank you for your interest in our work! 

To train Graphist-base, it requires about 40 hours on 8 $\times$ 80G A100 GPUs without using in-house data. 

The timeline for releasing the code & checkpoints has not yet been determined. We are actively working on detaching the code from our internal framework, which involves scrutiny from the company and a substantial amount of re-coding. Meanwhile, once the training data mentioned in the paper is organized, you may be able to easily reproduce the results using other open LMM training frameworks. 😌
